### PR TITLE
fix: Add global unhandledRejection handler

### LINKED ISSUE #173: Unhandled promise rejection if tag exists
## Problem
When running action we get unhandled promise rejection when tag already exist
`fatal: tag '1.51.0' already exists
(node:1595) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/git' failed with exit code 128
    at ExecState._setResult (/home/runner/work/_actions/lidofinance/conventional-changelog-action/v3.11.0/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/lidofinance/conventional-changelog-action/v3.11.0/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/lidofinance/conventional-changelog-action/v3.11.0/node_modules/@actions/exec/lib/toolrunner.js:469:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)`
At the same time action completes successfully with no outputs set.

 ## Possible solution
 We can add
 `process.on('unhandledRejection', (reason, promise) => {
  console.log('Unhandled Rejection at:', promise, 'reason:', reason);
  core.setFailed(reason);
});`
So that all unhandled rejections will result in action failure

### PR DESCRIPTION
**Pull request by dgusakov**
Resolves https://github.com/TriPSs/conventional-changelog-action/issues/173

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -25,6 +25,13 @@ async function handleVersioningByExtension(ext, file, versionPath, releaseType)
 
 async function run() {
   try {
+
+    process.on('unhandledRejection', (reason, promise) => {
```
Comment (TriPSs) [inline src/index.js]: Maybe nicer to add this all the way at the bottom before `run` is called? Also maybe just pass the error directly to `console.log` and `core.setFailed`?

Comment (dgusakov) [reply src/index.js]: Moved.
Passing reason directly to the `console.log` and `core.setFailed` will result in casting it to a simple string and loosing stack trace. I suppose it is not the best option.
